[[pokemon]]
name = ""
nickname = ""
primary = ""
secondary = ""
level = 0
moves = [""]
currentHP = 0
HP = 0
Attack = 0
Defense = 0
Sp. Attack = 0
Sp. Defense = 0
Speed = 0

[[pokemon]]
name = ""
nickname = ""
primary = ""
secondary = ""
level = 0
moves = [""]
currentHP = 0
HP = 0
Attack = 0
Defense = 0
Sp. Attack = 0
Sp. Defense = 0
Speed = 0

[[pokemon]]
name = ""
nickname = ""
primary = ""
secondary = ""
level = 0
moves = [""]
currentHP = 0
HP = 0
Attack = 0
Defense = 0
Sp. Attack = 0
Sp. Defense = 0
Speed = 0

[[pokemon]]
name = ""
nickname = ""
primary = ""
secondary = ""
level = 0
moves = [""]
currentHP = 0
HP = 0
Attack = 0
Defense = 0
Sp. Attack = 0
Sp. Defense = 0
Speed = 0

[[pokemon]]
name = ""
nickname = ""
primary = ""
secondary = ""
level = 0
moves = [""]
currentHP = 0
HP = 0
Attack = 0
Defense = 0
Sp. Attack = 0
Sp. Defense = 0
Speed = 0

[[pokemon]]
name = ""
nickname = ""
primary = ""
secondary = ""
level = 0
moves = [""]
currentHP = 0
HP = 0
Attack = 0
Defense = 0
Sp. Attack = 0
Sp. Defense = 0
Speed = 0

[badges]
earned = [""]

[items]
money = 1500
pokeballs = 10
potions = 5